// GENERATED by design/build.mjs from design/tokens.json — do not edit.
// House Pour 1.0.0 · https://lucianlabs.ca/branding/house-pour.md

package ca.lucianlabs.housepour

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class HPShadow(val color: Color, val x: Dp, val y: Dp, val blur: Dp, val spread: Dp)

enum class HPFace { DISPLAY, BRAND, MONO, BODY }

/**
 * One stop of the spectrogram ramp (PRODUCT 2.11.1). [at] is 0..1 along the ramp; [argb] is straight
 * (non-premultiplied) 8-bit ARGB, which is what both the interpolator and Bitmap.setPixels want.
 */
data class HPRampStop(val at: Float, val argb: Int) {
    val color: Color get() = Color(argb)
}

/** size in sp, tracking in em, lineHeight multiplier. */
data class HPTextStyle(
    val face: HPFace,
    val size: Float,
    val weight: Int,
    val lineHeight: Float,
    val tracking: Float,
    val uppercase: Boolean,
)

object HPTokens {
    const val VERSION = "1.0.0"
    const val BORDER_WIDTH = 1

    object Colors {
    /** #f7f5ef */
    val bg = Color(0xFFF7F5EF)
    /** #f1eee6 */
    val bg2 = Color(0xFFF1EEE6)
    /** #fffefa */
    val panel = Color(0xFFFFFEFA)
    /** #262319 */
    val ink = Color(0xFF262319)
    /** #71695a */
    val muted = Color(0xFF71695A)
    /** #a79f8d */
    val faint = Color(0xFFA79F8D)
    /** rgba(38, 35, 25, 0.11) */
    val line = Color(0x1C262319)
    /** rgba(38, 35, 25, 0.2) */
    val line2 = Color(0x33262319)
    /** #a4813b */
    val accent = Color(0xFFA4813B)
    /** #c9a961 */
    val accent2 = Color(0xFFC9A961)
    /** rgba(164, 129, 59, 0.14) */
    val accentSoft = Color(0x24A4813B)
    /** #3c7a52 */
    val good = Color(0xFF3C7A52)
    /** #a03d38 */
    val bad = Color(0xFFA03D38)
    /** #8f6fc7 */
    val violet = Color(0xFF8F6FC7)
    /** rgba(38, 35, 25, 0.4) */
    val scrim = Color(0x66262319)
    /** #b3903f */
    val primaryGradientStart = Color(0xFFB3903F)
    /** #97742f */
    val primaryGradientEnd = Color(0xFF97742F)
    /** #fffdf6 */
    val primaryText = Color(0xFFFFFDF6)
    /** #35311f */
    val charcoalGradientStart = Color(0xFF35311F)
    /** #23211a */
    val charcoalGradientEnd = Color(0xFF23211A)
    /** #f6f2e8 */
    val charcoalText = Color(0xFFF6F2E8)
    /** #fffef9 */
    val inputBg = Color(0xFFFFFEF9)
    /** #26231a */
    val toastBg = Color(0xFF26231A)
    /** #f6f2e8 */
    val toastText = Color(0xFFF6F2E8)
    /** rgba(255, 253, 246, 0.12) */
    val toastLine = Color(0x1FFFFDF6)
    /** rgba(250, 248, 243, 0.85) */
    val topbarBg = Color(0xD9FAF8F3)
    /** #faf8f3 */
    val backdropTop = Color(0xFFFAF8F3)
    /** #f5f2ea */
    val backdropMid = Color(0xFFF5F2EA)
    /** #f2eee4 */
    val backdropBottom = Color(0xFFF2EEE4)
    /** rgba(201, 169, 97, 0.10) */
    val washGold = Color(0x1AC9A961)
    /** rgba(143, 111, 199, 0.05) */
    val washViolet = Color(0x0D8F6FC7)
    }
    object Radius {
    val card = 16.dp
    val input = 12.dp
    val media = 12.dp
    val pill = 999.dp
    }
    object Space {
    val columnMax = 540.dp
    val columnSide = 14.dp
    val cardPad = 20.dp
    val cardGap = 16.dp
    val rowPad = 14.dp
    val topbarY = 14.dp
    val topbarX = 22.dp
    val topbarBottom = 18.dp
    val buttonY = 14.dp
    val buttonX = 20.dp
    val buttonSmY = 9.dp
    val buttonSmX = 16.dp
    val inputY = 13.dp
    val inputX = 15.dp
    val inputBottom = 12.dp
    val labelBottom = 6.dp
    val pillY = 4.dp
    val pillX = 10.dp
    val tabsPad = 4.dp
    val tabsGap = 4.dp
    val tabY = 10.dp
    val tabX = 8.dp
    val tabsBottom = 16.dp
    val btnRowGap = 10.dp
    val rowGap = 10.dp
    val touchMin = 40.dp
    val stripHeight = 44.dp
    val kebabDot = 4.dp
    val kebabDotGap = 3.dp
    val menuWidth = 240.dp
    val menuDismissDrag = 40.dp
    val avatarRow = 36.dp
    val avatarProfile = 72.dp
    val bottomSafe = 96.dp
    }
    object Shadow {
    val contact = HPShadow(Color(0x0A262319), x = 0.dp, y = 1.dp, blur = 2.dp, spread = 0.dp)
    val cast = HPShadow(Color(0x2E262319), x = 0.dp, y = 14.dp, blur = 34.dp, spread = -18.dp)
    val primaryButton = HPShadow(Color(0xA6A4813B), x = 0.dp, y = 10.dp, blur = 22.dp, spread = -12.dp)
    val charcoalButton = HPShadow(Color(0x8C262319), x = 0.dp, y = 10.dp, blur = 22.dp, spread = -14.dp)
    val toast = HPShadow(Color(0x80262319), x = 0.dp, y = 16.dp, blur = 36.dp, spread = -12.dp)
    }
    /** res/font resource names (Android requires lowercase_snake). Synced by build.mjs --sync. */
    object FontRes {
    const val CORMORANTGARAMONDMEDIUM = "cormorant_garamond_medium" // CormorantGaramond-Medium.ttf
    const val CORMORANTGARAMONDSEMIBOLD = "cormorant_garamond_semi_bold" // CormorantGaramond-SemiBold.ttf
    const val CORMORANTGARAMONDBOLD = "cormorant_garamond_bold" // CormorantGaramond-Bold.ttf
    const val CORMORANTGARAMONDMEDIUMITALIC = "cormorant_garamond_medium_italic" // CormorantGaramond-MediumItalic.ttf
    const val KAUSHANSCRIPTREGULAR = "kaushan_script_regular" // KaushanScript-Regular.ttf
    const val INCONSOLATAREGULAR = "inconsolata_regular" // Inconsolata-Regular.ttf
    const val INCONSOLATASEMIBOLD = "inconsolata_semi_bold" // Inconsolata-SemiBold.ttf
    }
    object Type {
    val wordmark = HPTextStyle(HPFace.BRAND, size = 48f, weight = 400, lineHeight = 1.05f, tracking = 0f, uppercase = false)
    val brand = HPTextStyle(HPFace.BRAND, size = 27.2f, weight = 400, lineHeight = 1f, tracking = 0f, uppercase = false)
    val h1 = HPTextStyle(HPFace.DISPLAY, size = 33.6f, weight = 600, lineHeight = 1.12f, tracking = 0.01f, uppercase = false)
    val h2 = HPTextStyle(HPFace.DISPLAY, size = 25.6f, weight = 600, lineHeight = 1.12f, tracking = 0.01f, uppercase = false)
    val figure = HPTextStyle(HPFace.DISPLAY, size = 57.6f, weight = 600, lineHeight = 1f, tracking = 0.01f, uppercase = false)
    val totals = HPTextStyle(HPFace.DISPLAY, size = 20f, weight = 600, lineHeight = 1.2f, tracking = 0f, uppercase = false)
    val totalsAmount = HPTextStyle(HPFace.DISPLAY, size = 21.6f, weight = 600, lineHeight = 1.2f, tracking = 0f, uppercase = false)
    val sectionMark = HPTextStyle(HPFace.BODY, size = 11.2f, weight = 700, lineHeight = 1.2f, tracking = 0.22f, uppercase = true)
    val fieldLabel = HPTextStyle(HPFace.BODY, size = 10.56f, weight = 700, lineHeight = 1.2f, tracking = 0.18f, uppercase = true)
    val button = HPTextStyle(HPFace.BODY, size = 12.48f, weight = 700, lineHeight = 1.2f, tracking = 0.14f, uppercase = true)
    val buttonSm = HPTextStyle(HPFace.BODY, size = 10.56f, weight = 700, lineHeight = 1.2f, tracking = 0.14f, uppercase = true)
    val tab = HPTextStyle(HPFace.BODY, size = 11.2f, weight = 700, lineHeight = 1.2f, tracking = 0.16f, uppercase = true)
    val pill = HPTextStyle(HPFace.BODY, size = 9.92f, weight = 700, lineHeight = 1.2f, tracking = 0.14f, uppercase = true)
    val body = HPTextStyle(HPFace.BODY, size = 16f, weight = 400, lineHeight = 1.5f, tracking = 0f, uppercase = false)
    val bodyStrong = HPTextStyle(HPFace.BODY, size = 16f, weight = 600, lineHeight = 1.5f, tracking = 0f, uppercase = false)
    val small = HPTextStyle(HPFace.BODY, size = 13.6f, weight = 400, lineHeight = 1.5f, tracking = 0f, uppercase = false)
    val toast = HPTextStyle(HPFace.BODY, size = 13.6f, weight = 600, lineHeight = 1.3f, tracking = 0f, uppercase = false)
    val input = HPTextStyle(HPFace.BODY, size = 16f, weight = 400, lineHeight = 1.3f, tracking = 0f, uppercase = false)
    val mono = HPTextStyle(HPFace.MONO, size = 14.4f, weight = 400, lineHeight = 1.5f, tracking = 0f, uppercase = false)
    val monoSmall = HPTextStyle(HPFace.MONO, size = 12.8f, weight = 400, lineHeight = 1.5f, tracking = 0f, uppercase = false)
    }
    /**
     * PRODUCT 2.11.1 — the spectrogram strip's data ramp, the one gradient in the look that carries data.
     * Interpolation is hand-written (HPRamp); only the stops are generated, so all three platforms share
     * them exactly.
     */
    object Ramp {
        val stops: List<HPRampStop> = listOf(
        HPRampStop(0f, 0x00262319.toInt()), // line2
        HPRampStop(0.28f, 0x33262319.toInt()), // line2
        HPRampStop(0.55f, 0xFF71695A.toInt()), // muted
        HPRampStop(0.82f, 0xFFA4813B.toInt()), // accent
        HPRampStop(1f, 0xFFC9A961.toInt()), // accent2
        )
    }
    object Motion {
        const val COLOR_MS = 150
        const val PRESS_MS = 50
        const val TOAST_MS = 200
        val pressTranslateY = 1.dp
    }
}
