#!/usr/bin/env node
/* House Pour kit — build.
 *
 * ONE token file (tokens.json) → three generated token modules, so the iOS,
 * Android and web builds cannot drift from each other or from the brand:
 *
 *   swift/HousePour/HousePourTokens.swift   SwiftUI  (Color, Font names, metrics, type ramp)
 *   kotlin/housepour/HousePourTokens.kt     Compose  (Color, metrics, type ramp)
 *   web/house-pour.css                      CSS      (@font-face for vendored fonts + upstream stylesheet)
 *
 * Components are NOT generated — each platform keeps a hand-written component
 * library next to its tokens file (see COMPONENTS.md for the shared list and
 * rules). Only values are generated.
 *
 *   node build.mjs            regenerate the three token modules
 *   node build.mjs --sync     also copy fonts + css into the app trees
 *   node build.mjs --pull     diff tokens.json against the live brands.json
 *
 * No dependencies. No bundler.
 */

import { readFile, writeFile, mkdir, copyFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const repo = join(root, '..');
const T = JSON.parse(await readFile(join(root, 'tokens.json'), 'utf8'));
const args = new Set(process.argv.slice(2));

const HEADER = (lang) =>
  `${lang === 'css' ? '/*' : '//'} GENERATED by design/build.mjs from design/tokens.json — do not edit.
${lang === 'css' ? '  ' : '//'} House Pour ${T.version} · ${T.upstream.spec}${lang === 'css' ? ' */' : ''}
`;

// ── colour parsing ─────────────────────────────────────────────────────────

function parseColor(v) {
  if (v.startsWith('#')) {
    const h = v.slice(1);
    const n = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
    return { r: parseInt(n.slice(0, 2), 16), g: parseInt(n.slice(2, 4), 16), b: parseInt(n.slice(4, 6), 16), a: 1 };
  }
  const m = v.match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+))?\s*\)/);
  if (!m) throw new Error(`Unparseable colour: ${v}`);
  return { r: +m[1], g: +m[2], b: +m[3], a: m[4] === undefined ? 1 : +m[4] };
}
const f3 = (x) => (Math.round(x * 1000) / 1000).toString();
const hex2 = (n) => n.toString(16).padStart(2, '0').toUpperCase();

// ── Swift ──────────────────────────────────────────────────────────────────

function swift() {
  const colors = Object.entries(T.color)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, v]) => {
      const c = parseColor(v);
      return `    /// ${v}\n    public static let ${k} = Color(red: ${f3(c.r / 255)}, green: ${f3(c.g / 255)}, blue: ${f3(c.b / 255)}, opacity: ${f3(c.a)})`;
    })
    .join('\n');

  const radius = Object.entries(T.radius).map(([k, v]) => `    public static let ${k}: CGFloat = ${v}`).join('\n');
  const space = Object.entries(T.space).filter(([k]) => !k.startsWith('$')).map(([k, v]) => `    public static let ${k}: CGFloat = ${v}`).join('\n');
  const shadow = Object.entries(T.shadow)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, s]) => {
      const c = parseColor(s.color);
      return `    public static let ${k} = HPShadow(color: Color(red: ${f3(c.r / 255)}, green: ${f3(c.g / 255)}, blue: ${f3(c.b / 255)}, opacity: ${f3(c.a)}), x: ${s.x}, y: ${s.y}, blur: ${s.blur}, spread: ${s.spread ?? 0})`;
    })
    .join('\n');

  const fontNames = `    // PostScript names. Display/brand/mono are bundled TTFs (design/fonts); body is the system Avenir Next.
    public static let displayMedium = "${T.font.display.files['500']}"
    public static let displaySemiBold = "${T.font.display.files['600']}"
    public static let displayBold = "${T.font.display.files['700']}"
    public static let displayMediumItalic = "${T.font.display.files['500i']}"
    public static let brand = "${T.font.brand.files['400']}"
    public static let monoRegular = "${T.font.mono.files['400']}"
    public static let monoSemiBold = "${T.font.mono.files['600']}"
    public static let bodyRegular = "${T.font.body.ios['400']}"
    public static let bodyMedium = "${T.font.body.ios['500']}"
    public static let bodyDemiBold = "${T.font.body.ios['600']}"
    public static let bodyBold = "${T.font.body.ios['700']}"
    /// Every bundled file, for UIAppFonts / registration checks.
    public static let bundledFiles = [${[...Object.values(T.font.display.files), ...Object.values(T.font.brand.files), ...Object.values(T.font.mono.files)].map((f) => `"${f}.ttf"`).join(', ')}]`;

  const type = Object.entries(T.type)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, s]) => `    public static let ${k} = HPTextStyle(face: .${s.face}, size: ${s.size}, weight: ${s.weight}, lineHeight: ${s.lineHeight}, tracking: ${s.tracking}, uppercase: ${!!s.uppercase})`)
    .join('\n');

  return `${HEADER('swift')}
import SwiftUI

public struct HPShadow {
    public let color: Color
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
}

public enum HPFace { case display, brand, mono, body }

public struct HPTextStyle {
    public let face: HPFace
    public let size: CGFloat
    public let weight: Int
    public let lineHeight: CGFloat   // multiplier
    public let tracking: CGFloat     // em
    public let uppercase: Bool
    public var trackingPoints: CGFloat { tracking * size }
    public var lineSpacing: CGFloat { max(0, size * lineHeight - size * 1.2) }
}

public enum HPTokens {
    public static let version = "${T.version}"
    public enum Colors {
${colors}
    }
    public enum Radius {
${radius}
    }
    public enum Space {
${space}
    }
    public enum Shadow {
${shadow}
    }
    public enum FontName {
${fontNames}
    }
    public enum Type {
${type}
    }
    public enum Motion {
        public static let color: Double = ${T.motion.colorMs / 1000}
        public static let press: Double = ${T.motion.pressMs / 1000}
        public static let toast: Double = ${T.motion.toastMs / 1000}
        public static let pressTranslateY: CGFloat = ${T.motion.pressTranslateY}
    }
    public static let borderWidth: CGFloat = ${T.border.width}
}
`;
}

// ── Kotlin ─────────────────────────────────────────────────────────────────

function kotlin() {
  const colors = Object.entries(T.color)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, v]) => {
      const c = parseColor(v);
      return `    /** ${v} */\n    val ${k} = Color(0x${hex2(Math.round(c.a * 255))}${hex2(c.r)}${hex2(c.g)}${hex2(c.b)})`;
    })
    .join('\n');
  const radius = Object.entries(T.radius).map(([k, v]) => `    val ${k} = ${v}.dp`).join('\n');
  const space = Object.entries(T.space).filter(([k]) => !k.startsWith('$')).map(([k, v]) => `    val ${k} = ${v}.dp`).join('\n');
  const shadow = Object.entries(T.shadow)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, s]) => {
      const c = parseColor(s.color);
      return `    val ${k} = HPShadow(Color(0x${hex2(Math.round(c.a * 255))}${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}), x = ${s.x}.dp, y = ${s.y}.dp, blur = ${s.blur}.dp, spread = ${s.spread ?? 0}.dp)`;
    })
    .join('\n');
  const type = Object.entries(T.type)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, s]) => `    val ${k} = HPTextStyle(HPFace.${s.face.toUpperCase()}, size = ${s.size}f, weight = ${s.weight}, lineHeight = ${s.lineHeight}f, tracking = ${s.tracking}f, uppercase = ${!!s.uppercase})`)
    .join('\n');
  const resNames = fontResNames();
  const fontRes = Object.entries(resNames).map(([file, res]) => `    const val ${camel(res).toUpperCase()} = "${res}" // ${file}.ttf`).join('\n');

  return `${HEADER('kotlin')}
package ca.lucianlabs.housepour

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class HPShadow(val color: Color, val x: Dp, val y: Dp, val blur: Dp, val spread: Dp)

enum class HPFace { DISPLAY, BRAND, MONO, BODY }

/** size in sp, tracking in em, lineHeight multiplier. */
data class HPTextStyle(
    val face: HPFace,
    val size: Float,
    val weight: Int,
    val lineHeight: Float,
    val tracking: Float,
    val uppercase: Boolean,
)

object HPTokens {
    const val VERSION = "${T.version}"
    const val BORDER_WIDTH = ${T.border.width}

    object Colors {
${colors}
    }
    object Radius {
${radius}
    }
    object Space {
${space}
    }
    object Shadow {
${shadow}
    }
    /** res/font resource names (Android requires lowercase_snake). Synced by build.mjs --sync. */
    object FontRes {
${fontRes}
    }
    object Type {
${type}
    }
    object Motion {
        const val COLOR_MS = ${T.motion.colorMs}
        const val PRESS_MS = ${T.motion.pressMs}
        const val TOAST_MS = ${T.motion.toastMs}
        val pressTranslateY = ${T.motion.pressTranslateY}.dp
    }
}
`;
}

function camel(s) { return s.replace(/[^a-z0-9]+([a-z0-9])/gi, (_, c) => c.toUpperCase()); }

function fontResNames() {
  const out = {};
  for (const face of ['display', 'brand', 'mono']) {
    for (const file of Object.values(T.font[face].files)) {
      out[file] = file.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/-/g, '_').toLowerCase();
    }
  }
  return out;
}

// ── CSS ────────────────────────────────────────────────────────────────────

function fontFaces(fontDir) {
  const rows = [];
  const add = (family, weight, style, file) =>
    rows.push(`@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('${fontDir}/${file}.woff2') format('woff2'), url('${fontDir}/${file}.ttf') format('truetype');
}`);
  for (const [w, file] of Object.entries(T.font.display.files)) add(T.font.display.family, parseInt(w, 10), w.endsWith('i') ? 'italic' : 'normal', file);
  for (const [w, file] of Object.entries(T.font.brand.files)) add(T.font.brand.family, w, 'normal', file);
  for (const [w, file] of Object.entries(T.font.mono.files)) add(T.font.mono.family, w, 'normal', file);
  return rows.join('\n');
}

async function css() {
  const base = await readFile(join(root, 'web', 'house-pour.base.css'), 'utf8');
  const typeVars = Object.entries(T.type)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, s]) => `  --type-${kebab(k)}: ${s.weight} ${s.size / 16}rem/${s.lineHeight} var(--font-${s.face});`)
    .join('\n');
  return `${HEADER('css')}
/* Vendored faces (design/fonts, SIL OFL). Upstream links Google Fonts; this kit
   self-hosts so the app works offline and makes no third-party request. */
${fontFaces('fonts')}

/* Type ramp as shorthand vars (weight size/line-height face) — the upstream
   stylesheet sets these on elements; the vars exist so app CSS can reuse a
   role without restating numbers. */
:root {
${typeVars}
  --space-card-pad: ${T.space.cardPad}px;
  --space-card-gap: ${T.space.cardGap}px;
  --space-column-max: ${T.space.columnMax}px;
  --space-column-side: ${T.space.columnSide}px;
  --radius-input: ${T.radius.input}px;
  --radius-media: ${T.radius.media}px;
  --scrim: ${T.color.scrim};
  --motion-color: ${T.motion.colorMs}ms;
  --motion-toast: ${T.motion.toastMs}ms;
}

${base}`;
}
function kebab(s) { return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase(); }

// ── write ──────────────────────────────────────────────────────────────────

async function out(path, content) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
  console.log('wrote', path.replace(repo + '/', ''));
}

await out(join(root, 'swift', 'HousePour', 'HousePourTokens.swift'), swift());
await out(join(root, 'kotlin', 'housepour', 'HousePourTokens.kt'), kotlin());
await out(join(root, 'web', 'house-pour.css'), await css());

if (args.has('--sync')) {
  // Android: res/font requires lowercase_snake filenames.
  const androidFont = join(repo, 'android', 'app', 'src', 'main', 'res', 'font');
  await mkdir(androidFont, { recursive: true });
  for (const [file, res] of Object.entries(fontResNames())) {
    await copyFile(join(root, 'fonts', `${file}.ttf`), join(androidFont, `${res}.ttf`));
  }
  console.log('synced fonts →', androidFont.replace(repo + '/', ''));

  // Web: vendor the stylesheet + fonts next to index.html (the deploy copies web/ only).
  const webVendor = join(repo, 'web', 'vendor');
  await mkdir(join(webVendor, 'fonts'), { recursive: true });
  await copyFile(join(root, 'web', 'house-pour.css'), join(webVendor, 'house-pour.css'));
  for (const f of await readdir(join(root, 'fonts'))) {
    if (f.endsWith('.woff2') || f.endsWith('.ttf') || f.startsWith('OFL')) await copyFile(join(root, 'fonts', f), join(webVendor, 'fonts', f));
  }
  console.log('synced css + fonts →', webVendor.replace(repo + '/', ''));
}

if (args.has('--pull')) {
  const res = await fetch(T.upstream.tokens);
  const live = (await res.json()).looks['house-pour'].tokens;
  const map = { '--bg': 'bg', '--bg-2': 'bg2', '--panel': 'panel', '--ink': 'ink', '--muted': 'muted', '--faint': 'faint', '--line': 'line', '--line-2': 'line2', '--accent': 'accent', '--accent-2': 'accent2', '--accent-soft': 'accentSoft', '--good': 'good', '--bad': 'bad' };
  let drift = 0;
  for (const [k, local] of Object.entries(map)) {
    if (live[k] && live[k].replace(/\s/g, '') !== T.color[local].replace(/\s/g, '')) {
      drift++;
      console.log(`DRIFT ${k}: upstream ${live[k]} · local ${T.color[local]}`);
    }
  }
  console.log(drift ? `${drift} token(s) drifted from upstream` : 'tokens match upstream');
}
