#!/usr/bin/env node
/* House Pour kit — web token supplement.
 *
 * house-pour.css (generated by ../build.mjs) carries the upstream stylesheet
 * and a handful of vars. The app CSS also needs the spacing, avatar, touch,
 * motion and shadow tokens that upstream only bakes into element rules. This
 * emits EVERY token in tokens.json as a `--hp-*` custom property so web
 * component code never restates a value:
 *
 *   design/web/tokens.css   → copied to web/css/tokens.css
 *
 *   node design/web/tokens.build.mjs
 *
 * No dependencies. Upstream names (--bg, --ink, --accent, --radius …) stay
 * authoritative where they exist; --hp-* is the superset.
 */
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const design = join(here, '..');
const repo = join(design, '..');
const T = JSON.parse(await readFile(join(design, 'tokens.json'), 'utf8'));

const kebab = (s) => s.replace(/([A-Z])/g, '-$1').replace(/(\d)i$/, '$1-i').toLowerCase();
const entries = (o) => Object.entries(o).filter(([k]) => !k.startsWith('$'));
const px = (n) => `${n}px`;
/* Type sizes are emitted in rem (tokens.json sizes assume 16px) so the ramp
   follows the browser's font-size preference and scales with the upstream
   rem-based element rules (COMPONENTS rule 7). Space/radius/shadow stay px. */
const rem = (n) => `${Math.round((n / 16) * 10000) / 10000}rem`;
/* rgba() with the alpha multiplied — HPModal's "cast opacity ×1.5". */
const scaleAlpha = (color, k) =>
  color.replace(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)/, (_, r, g, b, a) => `rgba(${r}, ${g}, ${b}, ${Math.round(Math.min(1, +a * k) * 1000) / 1000})`);

const lines = [];
lines.push(`/* GENERATED by design/web/tokens.build.mjs from design/tokens.json — do not edit.`);
lines.push(`   House Pour ${T.version} web token supplement. Every value here is a token. */`);
lines.push(':root {');
lines.push('  /* colour */');
for (const [k, v] of entries(T.color)) lines.push(`  --hp-color-${kebab(k)}: ${v};`);
lines.push('  /* radius */');
for (const [k, v] of entries(T.radius)) lines.push(`  --hp-radius-${kebab(k)}: ${px(v)};`);
lines.push('  /* border */');
for (const [k, v] of entries(T.border)) lines.push(`  --hp-border-${kebab(k)}: ${px(v)};`);
lines.push('  /* shadow */');
for (const [k, s] of entries(T.shadow)) {
  lines.push(`  --hp-shadow-${kebab(k)}: ${px(s.x)} ${px(s.y)} ${px(s.blur)} ${px(s.spread ?? 0)} ${s.color};`);
}
{
  /* COMPONENTS.md HPModal: the card shadow with the cast layer deepened ×1.5 */
  const s = T.shadow.cast;
  lines.push(`  --hp-shadow-cast-modal: ${px(s.x)} ${px(s.y)} ${px(s.blur)} ${px(s.spread ?? 0)} ${scaleAlpha(s.color, 1.5)};`);
}
lines.push('  /* space (4px rhythm) */');
for (const [k, v] of entries(T.space)) lines.push(`  --hp-space-${kebab(k)}: ${px(v)};`);
lines.push('  /* faces */');
for (const [k, f] of entries(T.font)) lines.push(`  --hp-font-${kebab(k)}: ${f.css};`);
lines.push('  /* type ramp: size (rem) / line-height / weight / tracking per role */');
for (const [k, s] of entries(T.type)) {
  const name = kebab(k);
  lines.push(`  --hp-type-${name}-size: ${rem(s.size)};`);
  lines.push(`  --hp-type-${name}-weight: ${s.weight};`);
  lines.push(`  --hp-type-${name}-line: ${s.lineHeight};`);
  lines.push(`  --hp-type-${name}-tracking: ${s.tracking}em;`);
  lines.push(`  --hp-type-${name}-face: var(--hp-font-${kebab(s.face)});`);
}
lines.push('  /* motion */');
for (const [k, v] of entries(T.motion)) {
  lines.push(`  --hp-motion-${kebab(k)}: ${k.endsWith('Ms') ? `${v}ms` : px(v)};`);
}
lines.push('}');
lines.push('');

const css = lines.join('\n');
await writeFile(join(here, 'tokens.css'), css);
await mkdir(join(repo, 'web', 'css'), { recursive: true });
await copyFile(join(here, 'tokens.css'), join(repo, 'web', 'css', 'tokens.css'));
console.log('wrote design/web/tokens.css → web/css/tokens.css');
