// GENERATED by design/build.mjs from design/tokens.json — do not edit.
// House Pour 1.0.0 · https://lucianlabs.ca/branding/house-pour.md

import SwiftUI

public struct HPShadow {
    public let color: Color
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
}

public enum HPFace { case display, brand, mono, body }

public struct HPTextStyle {
    public let face: HPFace
    public let size: CGFloat
    public let weight: Int
    public let lineHeight: CGFloat   // multiplier
    public let tracking: CGFloat     // em
    public let uppercase: Bool
    public var trackingPoints: CGFloat { tracking * size }
    public var lineSpacing: CGFloat { max(0, size * lineHeight - size * 1.2) }
}

public enum HPTokens {
    public static let version = "1.0.0"
    public enum Colors {
    /// #f7f5ef
    public static let bg = Color(red: 0.969, green: 0.961, blue: 0.937, opacity: 1)
    /// #f1eee6
    public static let bg2 = Color(red: 0.945, green: 0.933, blue: 0.902, opacity: 1)
    /// #fffefa
    public static let panel = Color(red: 1, green: 0.996, blue: 0.98, opacity: 1)
    /// #262319
    public static let ink = Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 1)
    /// #71695a
    public static let muted = Color(red: 0.443, green: 0.412, blue: 0.353, opacity: 1)
    /// #a79f8d
    public static let faint = Color(red: 0.655, green: 0.624, blue: 0.553, opacity: 1)
    /// rgba(38, 35, 25, 0.11)
    public static let line = Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.11)
    /// rgba(38, 35, 25, 0.2)
    public static let line2 = Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.2)
    /// #a4813b
    public static let accent = Color(red: 0.643, green: 0.506, blue: 0.231, opacity: 1)
    /// #c9a961
    public static let accent2 = Color(red: 0.788, green: 0.663, blue: 0.38, opacity: 1)
    /// rgba(164, 129, 59, 0.14)
    public static let accentSoft = Color(red: 0.643, green: 0.506, blue: 0.231, opacity: 0.14)
    /// #3c7a52
    public static let good = Color(red: 0.235, green: 0.478, blue: 0.322, opacity: 1)
    /// #a03d38
    public static let bad = Color(red: 0.627, green: 0.239, blue: 0.22, opacity: 1)
    /// #8f6fc7
    public static let violet = Color(red: 0.561, green: 0.435, blue: 0.78, opacity: 1)
    /// rgba(38, 35, 25, 0.4)
    public static let scrim = Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.4)
    /// #b3903f
    public static let primaryGradientStart = Color(red: 0.702, green: 0.565, blue: 0.247, opacity: 1)
    /// #97742f
    public static let primaryGradientEnd = Color(red: 0.592, green: 0.455, blue: 0.184, opacity: 1)
    /// #fffdf6
    public static let primaryText = Color(red: 1, green: 0.992, blue: 0.965, opacity: 1)
    /// #35311f
    public static let charcoalGradientStart = Color(red: 0.208, green: 0.192, blue: 0.122, opacity: 1)
    /// #23211a
    public static let charcoalGradientEnd = Color(red: 0.137, green: 0.129, blue: 0.102, opacity: 1)
    /// #f6f2e8
    public static let charcoalText = Color(red: 0.965, green: 0.949, blue: 0.91, opacity: 1)
    /// #fffef9
    public static let inputBg = Color(red: 1, green: 0.996, blue: 0.976, opacity: 1)
    /// #26231a
    public static let toastBg = Color(red: 0.149, green: 0.137, blue: 0.102, opacity: 1)
    /// #f6f2e8
    public static let toastText = Color(red: 0.965, green: 0.949, blue: 0.91, opacity: 1)
    /// rgba(255, 253, 246, 0.12)
    public static let toastLine = Color(red: 1, green: 0.992, blue: 0.965, opacity: 0.12)
    /// rgba(250, 248, 243, 0.85)
    public static let topbarBg = Color(red: 0.98, green: 0.973, blue: 0.953, opacity: 0.85)
    /// #faf8f3
    public static let backdropTop = Color(red: 0.98, green: 0.973, blue: 0.953, opacity: 1)
    /// #f5f2ea
    public static let backdropMid = Color(red: 0.961, green: 0.949, blue: 0.918, opacity: 1)
    /// #f2eee4
    public static let backdropBottom = Color(red: 0.949, green: 0.933, blue: 0.894, opacity: 1)
    /// rgba(201, 169, 97, 0.10)
    public static let washGold = Color(red: 0.788, green: 0.663, blue: 0.38, opacity: 0.1)
    /// rgba(143, 111, 199, 0.05)
    public static let washViolet = Color(red: 0.561, green: 0.435, blue: 0.78, opacity: 0.05)
    }
    public enum Radius {
    public static let card: CGFloat = 16
    public static let input: CGFloat = 12
    public static let media: CGFloat = 12
    public static let pill: CGFloat = 999
    }
    public enum Space {
    public static let columnMax: CGFloat = 540
    public static let columnSide: CGFloat = 14
    public static let cardPad: CGFloat = 20
    public static let cardGap: CGFloat = 16
    public static let rowPad: CGFloat = 14
    public static let topbarY: CGFloat = 14
    public static let topbarX: CGFloat = 22
    public static let topbarBottom: CGFloat = 18
    public static let buttonY: CGFloat = 14
    public static let buttonX: CGFloat = 20
    public static let buttonSmY: CGFloat = 9
    public static let buttonSmX: CGFloat = 16
    public static let inputY: CGFloat = 13
    public static let inputX: CGFloat = 15
    public static let inputBottom: CGFloat = 12
    public static let labelBottom: CGFloat = 6
    public static let pillY: CGFloat = 4
    public static let pillX: CGFloat = 10
    public static let tabsPad: CGFloat = 4
    public static let tabsGap: CGFloat = 4
    public static let tabY: CGFloat = 10
    public static let tabX: CGFloat = 8
    public static let tabsBottom: CGFloat = 16
    public static let btnRowGap: CGFloat = 10
    public static let rowGap: CGFloat = 10
    public static let touchMin: CGFloat = 40
    public static let kebabDot: CGFloat = 4
    public static let kebabDotGap: CGFloat = 3
    public static let menuWidth: CGFloat = 240
    public static let menuDismissDrag: CGFloat = 40
    public static let avatarRow: CGFloat = 36
    public static let avatarProfile: CGFloat = 72
    public static let bottomSafe: CGFloat = 96
    }
    public enum Shadow {
    public static let contact = HPShadow(color: Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.04), x: 0, y: 1, blur: 2, spread: 0)
    public static let cast = HPShadow(color: Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.18), x: 0, y: 14, blur: 34, spread: -18)
    public static let primaryButton = HPShadow(color: Color(red: 0.643, green: 0.506, blue: 0.231, opacity: 0.65), x: 0, y: 10, blur: 22, spread: -12)
    public static let charcoalButton = HPShadow(color: Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.55), x: 0, y: 10, blur: 22, spread: -14)
    public static let toast = HPShadow(color: Color(red: 0.149, green: 0.137, blue: 0.098, opacity: 0.5), x: 0, y: 16, blur: 36, spread: -12)
    }
    public enum FontName {
    // PostScript names. Display/brand/mono are bundled TTFs (design/fonts); body is the system Avenir Next.
    public static let displayMedium = "CormorantGaramond-Medium"
    public static let displaySemiBold = "CormorantGaramond-SemiBold"
    public static let displayBold = "CormorantGaramond-Bold"
    public static let displayMediumItalic = "CormorantGaramond-MediumItalic"
    public static let brand = "KaushanScript-Regular"
    public static let monoRegular = "Inconsolata-Regular"
    public static let monoSemiBold = "Inconsolata-SemiBold"
    public static let bodyRegular = "AvenirNext-Regular"
    public static let bodyMedium = "AvenirNext-Medium"
    public static let bodyDemiBold = "AvenirNext-DemiBold"
    public static let bodyBold = "AvenirNext-Bold"
    /// Every bundled file, for UIAppFonts / registration checks.
    public static let bundledFiles = ["CormorantGaramond-Medium.ttf", "CormorantGaramond-SemiBold.ttf", "CormorantGaramond-Bold.ttf", "CormorantGaramond-MediumItalic.ttf", "KaushanScript-Regular.ttf", "Inconsolata-Regular.ttf", "Inconsolata-SemiBold.ttf"]
    }
    public enum `Type` {
    public static let wordmark = HPTextStyle(face: .brand, size: 48, weight: 400, lineHeight: 1.05, tracking: 0, uppercase: false)
    public static let brand = HPTextStyle(face: .brand, size: 27.2, weight: 400, lineHeight: 1, tracking: 0, uppercase: false)
    public static let h1 = HPTextStyle(face: .display, size: 33.6, weight: 600, lineHeight: 1.12, tracking: 0.01, uppercase: false)
    public static let h2 = HPTextStyle(face: .display, size: 25.6, weight: 600, lineHeight: 1.12, tracking: 0.01, uppercase: false)
    public static let figure = HPTextStyle(face: .display, size: 57.6, weight: 600, lineHeight: 1, tracking: 0.01, uppercase: false)
    public static let totals = HPTextStyle(face: .display, size: 20, weight: 600, lineHeight: 1.2, tracking: 0, uppercase: false)
    public static let totalsAmount = HPTextStyle(face: .display, size: 21.6, weight: 600, lineHeight: 1.2, tracking: 0, uppercase: false)
    public static let sectionMark = HPTextStyle(face: .body, size: 11.2, weight: 700, lineHeight: 1.2, tracking: 0.22, uppercase: true)
    public static let fieldLabel = HPTextStyle(face: .body, size: 10.56, weight: 700, lineHeight: 1.2, tracking: 0.18, uppercase: true)
    public static let button = HPTextStyle(face: .body, size: 12.48, weight: 700, lineHeight: 1.2, tracking: 0.14, uppercase: true)
    public static let buttonSm = HPTextStyle(face: .body, size: 10.56, weight: 700, lineHeight: 1.2, tracking: 0.14, uppercase: true)
    public static let tab = HPTextStyle(face: .body, size: 11.2, weight: 700, lineHeight: 1.2, tracking: 0.16, uppercase: true)
    public static let pill = HPTextStyle(face: .body, size: 9.92, weight: 700, lineHeight: 1.2, tracking: 0.14, uppercase: true)
    public static let body = HPTextStyle(face: .body, size: 16, weight: 400, lineHeight: 1.5, tracking: 0, uppercase: false)
    public static let bodyStrong = HPTextStyle(face: .body, size: 16, weight: 600, lineHeight: 1.5, tracking: 0, uppercase: false)
    public static let small = HPTextStyle(face: .body, size: 13.6, weight: 400, lineHeight: 1.5, tracking: 0, uppercase: false)
    public static let toast = HPTextStyle(face: .body, size: 13.6, weight: 600, lineHeight: 1.3, tracking: 0, uppercase: false)
    public static let input = HPTextStyle(face: .body, size: 16, weight: 400, lineHeight: 1.3, tracking: 0, uppercase: false)
    public static let mono = HPTextStyle(face: .mono, size: 14.4, weight: 400, lineHeight: 1.5, tracking: 0, uppercase: false)
    public static let monoSmall = HPTextStyle(face: .mono, size: 12.8, weight: 400, lineHeight: 1.5, tracking: 0, uppercase: false)
    }
    public enum Motion {
        public static let color: Double = 0.15
        public static let press: Double = 0.05
        public static let toast: Double = 0.2
        public static let pressTranslateY: CGFloat = 1
    }
    public static let borderWidth: CGFloat = 1
}
