// Demo — the world object (PRODUCT.md §2.22.4: "The demo is a different object, not a mode").
//
// Everything a demo session reads comes from here. `DemoWorld` holds no reference to `TDClient`,
// imports no TDLib symbol, and has no code path to Telegram to miss — which is the point. A boolean
// checked at each call site has branches that can be forgotten; a substituted object has nowhere to
// forget one, and `DemoIsolationTests` fails the build if a TDLib import ever appears in this
// directory.
//
// It is also the whole of "nothing is saved on this device" (§2.22.5): the world lives in memory
// and writes to none of the homes a real session uses — no card cache, no feed cache, no cursors,
// no comment index, no `LocalStore` key at all. Leaving drops the object, and relaunching leaves
// the demo because there was never anything on disk to come back to.

import Foundation

@MainActor
final class DemoWorld {
    /// The moment the demo started, floored to the minute. Every fixture age is an offset from here
    /// rather than a fixed date, so §2.3's relative-time ladder reads correctly in a review a year
    /// from now.
    ///
    /// The flooring is what makes §2.22.1's table describe the number on the card. `PostHeader`
    /// renders the relative time from `TimelineView(.everyMinute)`, whose `context.date` is the last
    /// minute boundary and so trails the instant by up to 59 s, and `PostTime.relative` floors.
    /// Against ages that are exact multiples of their unit — `6 * minute`, `1 * day` — that lag
    /// costs a whole rung: the 6-minute post paints `5m ago` and the day-old one `23h ago` for most
    /// of the first minute of every demo. Anchoring the world to the same boundary the card renders
    /// on makes the elapsed time exactly the tabulated age, so "a wrong rounding is visible without
    /// arithmetic" (§2.22.1) is a statement about the screen and not only about the table.
    let startedAt: Date
    let media = DemoMedia()

    private(set) var nodes: [String: NodeInfo] = [:]
    private(set) var feeds: [String: FeedInfo] = [:]
    /// All fifteen, newest first — the order Feed paints them.
    private(set) var posts: [Post] = []
    /// Every post of every channel, including the nine feeds that never reach the main feed.
    private(set) var postsByChannel: [String: [Post]] = [:]
    /// Target key → the comments pointing at it, the same shape `CommentRepository` indexes by, so
    /// the thread walk is the app's own and not a second implementation.
    private(set) var commentIndex: [String: [Comment]] = [:]

    private(set) var myNode: MyNode
    private(set) var myCard: Card
    private(set) var myTitle: String

    // Discovery, precomputed: the demo's graph never changes, so there is nothing to walk.
    private(set) var direct: [NodeInfo] = []
    private(set) var nearby: [DirectoryEntry] = []
    private(set) var directory: [DirectoryEntry] = []
    private(set) var edges: [String: [String]] = [:]

    init(now: Date = Date()) {
        startedAt = Self.minuteBoundary(atOrBefore: now)
        let readerSpec = DemoFixtures.nodes[0]
        myCard = Card(name: readerSpec.name, bio: readerSpec.bio, link: nil,
                      isPublic: readerSpec.isPublic, feeds: readerSpec.feeds,
                      follows: readerSpec.follows, replies: readerSpec.replies)
        myTitle = readerSpec.name
        myNode = MyNode(chatId: Self.chatId(readerSpec.username),
                        supergroupId: -Self.chatId(readerSpec.username),
                        username: readerSpec.username,
                        pinnedMessageId: 1 << 20)
        buildFeeds()
        buildNodes()
        buildPosts()
        buildComments()
        buildDiscovery()
    }

    /// Drops every generated byte (§2.22.5). Called when the demo ends.
    func discard() { media.discard() }

    /// The minute boundary at or before `date` — the same instant `TimelineView(.everyMinute)`
    /// hands a post card while that minute lasts. See `startedAt`.
    static func minuteBoundary(atOrBefore date: Date) -> Date {
        Date(timeIntervalSince1970: (date.timeIntervalSince1970 / 60).rounded(.down) * 60)
    }

    // MARK: - Identity

    /// A stable negative chat id per username. Telegram's channel chat ids are negative too, so
    /// nothing about the shape is a lie; the value is derived rather than typed out so the fifteen
    /// nodes and sixteen channels cannot collide by a transcription slip.
    static func chatId(_ username: String) -> Int64 {
        Int64(bitPattern: DemoRender.seed(Username.key(username)) % 900_000_000) * -1 - 1_000_000_000
    }

    /// TDLib shifts server message ids left by 20 bits; `DeepLink.serverMessageId` shifts them
    /// back. Fixture ids are the numbers in the t.me links (§2.22.1's tables), so they get shifted
    /// the same way a real one would be.
    static func messageId(_ serverId: Int64) -> Int64 { serverId << 20 }

    // MARK: - Build

    private func buildFeeds() {
        for spec in DemoFixtures.feeds {
            // §2.22: two channels carry a generated plate as their photo, so §2.3's FIRST avatar
            // branch paints. The rest have no photo — which is honest, a fixture channel has none —
            // and fall to the initial over a seeded tint, §2.3's third branch.
            let photo = spec.hasPlate
                ? media.photo(key: spec.username + "/avatar", width: 320, height: 320)
                : nil
            var description = spec.bio
            if spec.verified { description = Backlink.appended(to: description, node: spec.owner) }
            feeds[Username.key(spec.username)] = FeedInfo(username: spec.username,
                                                          chatId: Self.chatId(spec.username),
                                                          title: spec.title,
                                                          description: description,
                                                          photo: photo,
                                                          fetchedAt: startedAt)
        }
    }

    private func buildNodes() {
        for spec in DemoFixtures.nodes {
            let card = Card(name: spec.name, bio: spec.bio, link: nil, isPublic: spec.isPublic,
                            feeds: spec.feeds, follows: spec.follows, replies: spec.replies)
            nodes[Username.key(spec.username)] = NodeInfo(username: spec.username,
                                                          chatId: Self.chatId(spec.username),
                                                          title: spec.name,
                                                          card: card,
                                                          state: .ok,
                                                          // No node carries a photograph of a
                                                          // person (§2.22): the initial over a
                                                          // seeded tint stands in for every one.
                                                          photo: nil,
                                                          fetchedAt: startedAt)
        }
    }

    private func buildPosts() {
        var all: [Post] = []
        for spec in DemoFixtures.posts {
            guard let feed = feeds[Username.key(spec.channel)] else { continue }
            all.append(post(spec, feed: feed))
        }
        posts = FeedOrder.sortedNewestFirst(all)
        // The +1 nodes' feeds are deliberately not in the main feed — the merge is the follow graph
        // — but their channels are still real, so a reviewer who opens `arto`'s profile finds posts
        // they never saw in Feed. One extra post per outlying channel, derived the same way.
        var byChannel: [String: [Post]] = [:]
        for p in posts { byChannel[p.sourceKey, default: []].append(p) }
        for spec in DemoFixtures.feeds where byChannel[Username.key(spec.username)] == nil {
            guard let feed = feeds[Username.key(spec.username)] else { continue }
            let outlier = DemoFixtures.PostSpec(channel: spec.username, id: 7,
                                                age: 3 * DemoFixtures.hour,
                                                text: outlierText(spec), body: .text)
            byChannel[Username.key(spec.username)] = [post(outlier, feed: feed)]
        }
        postsByChannel = byChannel
    }

    /// A single line per outlying channel, in that node's own voice. Deliberately plain: these
    /// exist so a +1 profile is not an empty screen, not to add a second feed to read.
    private func outlierText(_ spec: DemoFixtures.FeedSpec) -> String {
        let owner = nodes[Username.key(spec.owner)]?.displayName ?? spec.owner
        return "\(spec.title), by \(owner). You reach this feed at +1, so it is not in your feed."
    }

    private func post(_ spec: DemoFixtures.PostSpec, feed: FeedInfo) -> Post {
        let owner = nodes[Username.key(ownerOf(feed.username))]
        let messageId = Self.messageId(spec.id)
        let (media, albumIds) = mediaFor(spec, messageId: messageId)
        let reactions = DemoFixtures.reactionCount(id: spec.id)
        return Post(messageId: messageId,
                    chatId: feed.chatId,
                    sourceKey: feed.key,
                    sourceUsername: feed.username,
                    sourceTitle: feed.title,
                    sourcePhoto: feed.photo,
                    date: Int(startedAt.timeIntervalSince1970) - spec.age,
                    text: Self.richText(spec.text),
                    media: media,
                    albumId: albumIds.count > 1 ? spec.id : 0,
                    albumMessageIds: albumIds,
                    views: DemoFixtures.viewCount(id: spec.id),
                    reactions: reactions > 0 ? [Reaction(emoji: "\u{1F41F}", count: reactions)] : [],
                    forwardedFrom: nil, forwardedChatId: nil, forwardedUserId: nil,
                    isPending: false,
                    authorUsername: owner?.username,
                    authorName: owner?.displayName,
                    authorPhoto: owner?.photo)
    }

    private func ownerOf(_ channel: String) -> String {
        DemoFixtures.feeds.first { Username.key($0.username) == Username.key(channel) }?.owner ?? ""
    }

    /// The media list for a post, and the message ids that run parallel to it. Only the album has
    /// more than one, which is exactly the condition `ViewerRequest.links(of:)` tests.
    private func mediaFor(_ spec: DemoFixtures.PostSpec, messageId: Int64) -> ([PostMedia], [Int64]) {
        let key = "\(spec.channel)/\(spec.id)"
        switch spec.body {
        case .text:
            return ([], [messageId])
        case .audio(let title, let performer, let seconds):
            return ([.audio(file: media.audio(key: key, seconds: seconds),
                            title: title, performer: performer, duration: seconds)], [messageId])
        case .album(let aspects):
            var out: [PostMedia] = []
            var ids: [Int64] = []
            for (i, aspect) in aspects.enumerated() {
                let itemKey = "\(key)-\(i + 1)"
                let width = aspect.w * 240, height = aspect.h * 240
                let preview = media.photo(key: itemKey, width: width / 3, height: height / 3)
                let full = media.photo(key: itemKey, width: width, height: height)
                out.append(.photo(preview: preview, full: full))
                // Each album item is its own message, which is what makes paging the carousel
                // re-target the thread (§2.12).
                ids.append(Self.messageId(spec.id + Int64(i)))
            }
            return (out, ids)
        case .photo(let w, let h):
            let width = w * 900, height = h * 900
            return ([.photo(preview: media.photo(key: key, width: width / 3, height: height / 3),
                            full: media.photo(key: key, width: width, height: height))], [messageId])
        case .linkPreview(let url, let site, let title, let text):
            return ([.linkPreview(url: url, siteName: site, title: title, text: text,
                                  thumbnail: media.photo(key: key + "-link", width: 240, height: 240))],
                    [messageId])
        case .document(let name, let mime, let bytes):
            return ([.document(file: media.document(key: key, name: name, bytes: bytes, mimeType: mime),
                               thumbnail: nil)], [messageId])
        case .video(let seconds, let w, let h):
            return ([.video(file: media.clip(key: key, seconds: seconds, width: w, height: h),
                            thumbnail: media.photo(key: key + "-poster", width: w, height: h),
                            duration: seconds, width: w, height: h)], [messageId])
        case .animation(let seconds, let w, let h):
            return ([.animation(file: media.clip(key: key, seconds: seconds, width: w, height: h),
                                thumbnail: media.photo(key: key + "-poster", width: w, height: h),
                                duration: seconds, width: w, height: h)], [messageId])
        case .voice(let seconds):
            return ([.voice(file: media.audio(key: key, seconds: seconds), duration: seconds,
                            waveform: DemoRender.waveform(key: key, seconds: seconds))], [messageId])
        }
    }

    /// Fixture text is plain — no entities, so no invented link to nowhere. `RichTextView` renders
    /// one plain span exactly as it renders a real message's.
    static func richText(_ text: String) -> RichText {
        text.isEmpty ? .empty : RichText(spans: [RichSpan(text: text, kind: .plain, url: nil)])
    }

    private func buildComments() {
        for spec in DemoFixtures.comments {
            guard let owner = ownerOfComments(channel: spec.channel),
                  let key = CommentCodec.targetKey("https://t.me/" + spec.target) else { continue }
            let comment = Comment(channelUsername: spec.channel,
                                  chatId: Self.chatId(spec.channel),
                                  messageId: Self.messageId(spec.id),
                                  date: Int(startedAt.timeIntervalSince1970) - spec.age,
                                  target: "https://t.me/" + spec.target,
                                  body: spec.body,
                                  media: [],
                                  ownerUsername: owner.username,
                                  ownerTitle: owner.displayName,
                                  ownerPhoto: owner.photo,
                                  // `crate` is reached at +1 through `pell`, so their comment is in
                                  // §6.3 scope and wears the `+1` pill; the rest are direct follows.
                                  isPlusOne: !isDirectFollow(owner.username),
                                  isMine: Username.key(owner.username) == Username.key(DemoFixtures.reader))
            commentIndex[key, default: []].append(comment)
        }
    }

    private func ownerOfComments(channel: String) -> NodeInfo? {
        let key = Username.key(channel)
        guard let spec = DemoFixtures.nodes.first(where: { Username.key($0.replies) == key }) else { return nil }
        return nodes[Username.key(spec.username)]
    }

    private func isDirectFollow(_ username: String) -> Bool {
        myCard.follows(username)
    }

    private func buildDiscovery() {
        let myKey = Username.key(DemoFixtures.reader)
        let followKeys = myCard.follows.map(Username.key)
        direct = myCard.follows.compactMap { nodes[Username.key($0)] }

        var counts: [String: Int] = [:]
        var nextEdges: [String: [String]] = [:]
        for follow in direct {
            let theirs = follow.card?.follows ?? []
            nextEdges[follow.key] = theirs.map(Username.key)
            for f in theirs {
                let k = Username.key(f)
                guard k != myKey, !followKeys.contains(k) else { continue }
                counts[k, default: 0] += 1
            }
        }
        edges = nextEdges
        // Literally the function `DiscoveryRepository.walk` ranks with, so the demo's NEARBY order
        // is the app's rule and not a second copy of it (§2.22.1 writes the resulting order down).
        let ranked = NearbyOrder.ranked(counts)
        nearby = ranked.compactMap { key in
            nodes[key].map { DirectoryEntry(node: $0, followedByCount: counts[key] ?? 0) }
        }

        // DIRECTORY: the nodes in no walk. The reader is `public: no`, so they are absent from it
        // the way §2.4 requires — the same `isPublic` filter the real directory applies.
        let inWalk = Set(ranked + followKeys + [myKey])
        directory = DemoFixtures.nodes
            .compactMap { nodes[Username.key($0.username)] }
            .filter { !inWalk.contains($0.key) && ($0.card?.isPublic ?? false) }
            .sorted { $0.displayName.lowercased() < $1.displayName.lowercased() }
            .map { DirectoryEntry(node: $0, followedByCount: 0) }
    }

    // MARK: - Reads

    func node(_ username: String) -> NodeInfo? { nodes[Username.key(username)] }
    func feed(_ username: String) -> FeedInfo? { feeds[Username.key(username)] }

    /// The reader's feeds as Manage feeds and Setup see them (§2.2). Without these the card paints
    /// `No channels you can post to.` — false in the fixture world, where You lists `Notes` one tap
    /// earlier and feed post #6 is the reader's own post to it — and the per-feed toggles and their
    /// `Verify`, both named in §2.22.3's disabled list, would be missing rather than refusing.
    /// Nothing is queried: the world is the candidate list.
    var feedCandidates: [FeedCandidate] {
        myCard.feeds.compactMap { username in
            guard let feed = feeds[Username.key(username)] else { return nil }
            return FeedCandidate(chatId: feed.chatId, supergroupId: -feed.chatId,
                                 title: feed.title, username: feed.username,
                                 description: feed.description)
        }
    }

    /// Explore's search (§2.4): an exact `tgs_demo_*` username opens that profile, anything else
    /// misses. There is no prefix search to run against a fixed cast.
    func lookup(_ input: String) -> NodeInfo? {
        guard let username = Username.normalise(input) else { return nil }
        return node(username)
    }

    /// One page of the main feed. Eight at a time, so Feed loads a second page and then says
    /// `That's everything.` — pagination runs, and so does §2.18's rule that a fully-filtered page
    /// fetches the next one.
    func page(upTo count: Int) -> (posts: [Post], exhausted: Bool) {
        let limit = min(count, posts.count)
        return (Array(posts.prefix(limit)), limit >= posts.count)
    }

    /// One channel's posts (§2.6). `after` is the count already on screen, the same shape the real
    /// screen's cursor has — a demo has no message-id cursor because it has no history to page.
    func channelPage(_ username: String, after loaded: Int) -> (posts: [Post], exhausted: Bool) {
        let all = postsByChannel[Username.key(username)] ?? []
        let next = Array(all.dropFirst(loaded).prefix(DemoFixtures.pageSize))
        return (next, loaded + next.count >= all.count)
    }

    func post(link: String) -> Post? {
        guard let (channel, serverId) = CommentCodec.components(of: link) else { return nil }
        return (postsByChannel[Username.key(channel)] ?? []).first {
            DeepLink.serverMessageId($0.messageId) == serverId || $0.albumMessageIds.contains(Self.messageId(serverId))
        }
    }

    // MARK: - The demo sheet's rows (§2.22.5)

    var nodeCount: Int { DemoFixtures.nodes.count }
    /// `6 sources · 15 posts` — the six the main feed merges, not the sixteen channels that exist.
    var feedsRow: String {
        let sources = Set(posts.map(\.sourceKey)).count
        return "\(sources) source\(sources == 1 ? "" : "s") \u{00B7} \(posts.count) post\(posts.count == 1 ? "" : "s")"
    }
    /// `4 direct · 7 at +1`.
    var networkRow: String { "\(direct.count) direct \u{00B7} \(nearby.count) at +1" }
}
